POST http://localhost:8080/mkadia-api/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "schajjaoui2003@gmail.com",
    "password": "Soufianch@2211"
}


###
GET http://localhost:19120/api/v1